// lib/firebase_options.dart
// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for linux.');
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbEyzaBYjIVoWzYft6ax6xNpdVBfcaIbs',
    appId: '1:774025972537:web:2f2f207efafa295a9bb6e8',
    messagingSenderId: '774025972537',
    projectId: 'sozqor',
    authDomain: 'sozqor.firebaseapp.com',
    storageBucket: 'sozqor.firebasestorage.app',
    measurementId: 'G-WYQGRKZX9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWbxc8MwggmGCQaKQLL8KPWZdvbR41A0M',
    appId: '1:774025972537:android:a9b78107f6c9646b9bb6e8',
    messagingSenderId: '774025972537',
    projectId: 'sozqor',
    storageBucket: 'sozqor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOQMs3TW8x4HI_rdoYQXB4DkpmXFN0UJ0',
    appId: '1:774025972537:ios:7cc8307c156e4d949bb6e8',
    messagingSenderId: '774025972537',
    projectId: 'sozqor',
    storageBucket: 'sozqor.firebasestorage.app',
    iosBundleId: 'com.example.sozqorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOQMs3TW8x4HI_rdoYQXB4DkpmXFN0UJ0',
    appId: '1:774025972537:ios:7cc8307c156e4d949bb6e8',
    messagingSenderId: '774025972537',
    projectId: 'sozqor',
    storageBucket: 'sozqor.firebasestorage.app',
    iosBundleId: 'com.example.sozqorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbEyzaBYjIVoWzYft6ax6xNpdVBfcaIbs',
    appId: '1:774025972537:web:fe8ae94e928695039bb6e8',
    messagingSenderId: '774025972537',
    projectId: 'sozqor',
    authDomain: 'sozqor.firebaseapp.com',
    storageBucket: 'sozqor.firebasestorage.app',
    measurementId: 'G-3PBSSRPHZE',
  );
}